# Generated by Django 5.0 on 2024-05-01 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SchoolAdminApp', '0012_schoolresult'),
        ('common', '0002_schoolinformationonboarding_username'),
        ('core', '0011_alter_socialmedia_school_social_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('universalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.universalmodel')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('core.universalmodel',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('universalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.universalmodel')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_item', models.PositiveBigIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('grand_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('invoice_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('fee_for', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='STUDENT', max_length=10)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.schoolinformationonboarding')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.schoolsection')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('invoice_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.invoicetype')),
            ],
            bases=('core.universalmodel',),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('fees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SchoolAdminApp.feesinformation')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.invoice')),
            ],
        ),
    ]
