# Generated by Django 5.0 on 2024-01-03 14:53

import autoslug.fields
import common.utills
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updateAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolInformationOnBoarding",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(max_length=550)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=common.utills.get_school_info_onboard_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("S", "100 to 500 students"),
                            ("M", "100 to 1000 students"),
                            ("L", "100 to 2000 students"),
                            ("XL", "100 to 3000 students"),
                            ("XXL", "100 to 5000 students"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
            bases=("common.basemodel",),
        ),
    ]
