# Generated by Django 5.0 on 2024-03-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolinformationonboarding",
            name="username",
            field=models.CharField(
                default=1, editable=False, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
