# Generated by Django 5.0 on 2024-01-03 14:54

import autoslug.fields
import core.utills
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversalModel",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "active"), ("Inactive", "inactive")],
                        default="Active",
                        max_length=15,
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="User_who_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created Person",
                    ),
                ),
                (
                    "user_updated",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="The_User_who_Updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated Person",
                    ),
                ),
            ],
            bases=("common.basemodel",),
        ),
        migrations.CreateModel(
            name="AcademicInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("title", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "code_of_conducts",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Code of Conducts",
                    ),
                ),
                (
                    "guideline_for_parents",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Guideline for Parents",
                    ),
                ),
                (
                    "dress_code",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Dress Code",
                    ),
                ),
                (
                    "homework_and_lecture_documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_academic_homework_and_lecture_documents_pdf,
                        verbose_name="Homework and Class Lecture Documents",
                    ),
                ),
                (
                    "lesson_plan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_academic_lesson_plan_documents_pdf,
                        verbose_name="Lesson Plan",
                    ),
                ),
                (
                    "academic_calendar",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_academic_calendar_documents_pdf,
                        verbose_name="Academic Calendar",
                    ),
                ),
                (
                    "syllabus",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_academic_syllabus_documents_pdf,
                        verbose_name="Syllabus",
                    ),
                ),
                (
                    "class_routine",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_academic_class_routine_documents_pdf,
                        verbose_name="Class Routine",
                    ),
                ),
                (
                    "co_curricular_activities",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Co-curricular Activities",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_school_academic_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_academic_information",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_academic_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Academic Information",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="AlumniSection",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_alumni_section_slug,
                        unique=True,
                    ),
                ),
                (
                    "about_alumni",
                    models.TextField(
                        blank=True, null=True, verbose_name="About Alumni"
                    ),
                ),
                (
                    "alumni_events",
                    models.TextField(
                        blank=True, null=True, verbose_name="Alumni Events"
                    ),
                ),
                (
                    "alumni_news",
                    models.TextField(blank=True, null=True, verbose_name="Alumni News"),
                ),
                (
                    "school_alumni_section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_section_info",
                        to="common.schoolinformationonboarding",
                        verbose_name="School Website Alumni Information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Alumni Section Information",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "school_blog_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="blog_categories",
                        to="common.schoolinformationonboarding",
                        verbose_name="School Blog Category",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_blog_slug,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Content"),
                ),
                ("publish_date", models.DateTimeField(auto_now_add=True)),
                (
                    "school_blog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_website_blog_information",
                        to="common.schoolinformationonboarding",
                        verbose_name="School Website Blog Information",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="core.blogcategory", verbose_name="Categories"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Blog Posts",
                "ordering": ["-publish_date"],
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_blog_image_slug,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to=core.utills.get_blog_image
                    ),
                ),
                (
                    "blog_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_image_information",
                        to="core.blog",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "school_blog_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="blog_tags",
                        to="common.schoolinformationonboarding",
                        verbose_name="School Blog Tag",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="core.blogtag", verbose_name="Tags"
            ),
        ),
        migrations.CreateModel(
            name="NewsEvents",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "news_events_status",
                    models.CharField(
                        choices=[("news", "News"), ("event", "Event")],
                        db_index=True,
                        default="news",
                        max_length=100,
                        verbose_name="Type",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_news_events_slug,
                        unique=True,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_news_events_image,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="news_schools",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "News and Events",
                "ordering": ["-publish_date"],
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SchoolAddressInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core.utills.get_school_address_slug,
                        unique=True,
                    ),
                ),
                ("divisions", models.CharField(blank=True, max_length=255, null=True)),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "upazila",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Upozila or Thana",
                    ),
                ),
                (
                    "pourashava",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pourashava or City Corporation",
                    ),
                ),
                (
                    "union_parishad",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ward", models.CharField(blank=True, max_length=255, null=True)),
                ("mouza", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "village",
                    models.TextField(
                        blank=True,
                        max_length=555,
                        null=True,
                        verbose_name="Rasta/village",
                    ),
                ),
                (
                    "house_holding_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "post_office",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("post_code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "school_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_address_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Address Information",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SchoolAdmission",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("title", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "admission_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("class_one", "Class One"),
                            ("class_two", "Class Two"),
                            ("class_three", "Class Three"),
                            ("class_four", "Class Four"),
                            ("class_five", "Class Five"),
                            ("class_six", "Class Six"),
                            ("class_seven", "Class Seven"),
                            ("class_eight", "Class Eight"),
                            ("class_nine", "Class Nine"),
                            ("class_ten", "Class Ten"),
                            ("class_eleven", "Class Eleven"),
                            ("class_twelve", "Class Twelve"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Admission Class",
                    ),
                ),
                (
                    "admission_branch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prabhati", "প্রভাতী"),
                            ("diba", "দিবা"),
                            ("no_branch", "কোন শাখা নেই"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Admission Branch",
                    ),
                ),
                (
                    "admission_division",
                    models.CharField(
                        blank=True,
                        choices=[("bangla", "বাংলা"), ("english", "ইংরেজি")],
                        max_length=20,
                        null=True,
                        verbose_name="Admission Division",
                    ),
                ),
                (
                    "number_of_seats",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "limit_of_age",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "collection_of_prospectus",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "fill_the_application_form",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "online_admission_form_date_time",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "admission_process_college_information_website",
                    models.URLField(blank=True, null=True),
                ),
                (
                    "digital_lottery_time_information",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "admission_application_rules",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "other_description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("remark", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_admission_pdf,
                        verbose_name="PDF File",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_school_admission_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_admission_process",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Admission Process",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core.utills.get_school_class_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="School_Class_Information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Class",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SchoolContactInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core.utills.get_school_contact_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_contact_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "school_contact_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_contact_address",
                        to="core.schooladdressinformation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Contact Information",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SchoolSection",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core.utills.get_school_section_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_class_section",
                        to="core.schoolclass",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Class Section",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, null=True, verbose_name="Facebook URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, null=True, verbose_name="Twitter URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Instagram URL"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_social_media_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_social_media",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_info",
                        to="common.schoolinformationonboarding",
                        verbose_name="SocialMedia Website Information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Social Media Information",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteAbout",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Title"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                        verbose_name="School Short Description",
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                        verbose_name="School Long Description",
                    ),
                ),
                ("start_year", models.DateField()),
                (
                    "years_of_experience",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "vision",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="School Vision",
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="School Mission",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_about_slug,
                        unique=True,
                    ),
                ),
                (
                    "website_about_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_website_about_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website About",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteAboutFile",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_about_file_slug,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_about_file_image,
                    ),
                ),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="website_about_file_content",
                        to="core.websiteabout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website About File",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteAboutWinningAwards",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "awards_image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_about_file_awards_image,
                    ),
                ),
                (
                    "school_award",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_award_process",
                        to="core.websiteabout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website About Winning Awards",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteFunFactContent",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "years_of_experience",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "number_of_students",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "number_of_alumni",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "winning_awards",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "about_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="about_fun_fact_content",
                        to="core.websiteabout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website Fun Fact Content",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebSiteGalleryInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_get_gallery_image,
                        verbose_name="Image",
                    ),
                ),
                (
                    "school_website_gallery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_website_gallery_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website Gallery Images",
                "ordering": ["-createdAt"],
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteHomeSliderContent",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_home_slider_content_slug,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                (
                    "website_home_slider_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_website_slider_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website Home Slider Content",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteHomeSliderContentFile",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_home_slider_content_image,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_home_slider_content_file_slug,
                        unique=True,
                    ),
                ),
                (
                    "home_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="home_content_info",
                        to="core.websitehomeslidercontent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website Home Slider Content File",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "logo",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_school_website_logo,
                    ),
                ),
                (
                    "favicon",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_school_website_favicon,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core.utills.get_school_website_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_website_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website Information",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteManagingCommitteeMemberInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_managing_committee_member_slug,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255, verbose_name="Position")),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Biography"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "school_managing_committee_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ManagingCommitteeMember",
                        to="common.schoolinformationonboarding",
                        verbose_name="School Website ManagingCommitteeMember Information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ManagingCommitteeMember",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteStaffInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_staff_slug,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255, verbose_name="Position")),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Biography"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "school_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="staff",
                        to="common.schoolinformationonboarding",
                        verbose_name="School Website Staff Information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff Members",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteTeacherInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_teacher_slug,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255, verbose_name="Position")),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Biography"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "school_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="teachers",
                        to="common.schoolinformationonboarding",
                        verbose_name="School Website Teacher Information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Teachers",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebSiteFacultyInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_faculty_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="faculty_members",
                        to="common.schoolinformationonboarding",
                        verbose_name="School Faculty Website Information",
                    ),
                ),
                (
                    "managing_committee_member",
                    models.ManyToManyField(
                        blank=True,
                        related_name="Managing_Committee_Member_Information",
                        to="core.websitemanagingcommitteememberinformation",
                    ),
                ),
                (
                    "staff_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="faculty_membership",
                        to="core.websitemanagingcommitteememberinformation",
                        verbose_name="Staff Members",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="faculty_membership",
                        to="core.websiteteacherinformation",
                        verbose_name="Teachers",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Faculty Members",
            },
            bases=("core.universalmodel",),
        ),
        migrations.AddIndex(
            model_name="schooladdressinformation",
            index=models.Index(
                fields=["school_address"], name="core_school_school__d80be4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolcontactinformation",
            index=models.Index(
                fields=["school_contact"], name="core_school_school__553fe0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolcontactinformation",
            index=models.Index(
                fields=["school_contact_address"], name="core_school_school__fafa28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="websiteinformation",
            index=models.Index(
                fields=["school_website"], name="core_websit_school__f9f31b_idx"
            ),
        ),
    ]
