# Generated by Django 4.2.7 on 2023-12-01 13:55

import autoslug.fields
import core.utills
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversalModel",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "active"), ("Inactive", "inactive")],
                        default="Active",
                        max_length=15,
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="User_who_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created Person",
                    ),
                ),
                (
                    "user_updated",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="The_User_who_Updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated Person",
                    ),
                ),
            ],
            bases=("common.basemodel",),
        ),
        migrations.CreateModel(
            name="SchoolAddressInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core.utills.get_school_address_slug,
                        unique=True,
                    ),
                ),
                ("divisions", models.CharField(blank=True, max_length=255, null=True)),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "upazila",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Upozila or Thana",
                    ),
                ),
                (
                    "pourashava",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pourashava or City Corporation",
                    ),
                ),
                (
                    "union_parishad",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ward", models.CharField(blank=True, max_length=255, null=True)),
                ("mouza", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "village",
                    models.TextField(
                        blank=True,
                        max_length=555,
                        null=True,
                        verbose_name="Rasta/village",
                    ),
                ),
                (
                    "house_holding_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "post_office",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("post_code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "School Address Information",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core.utills.get_school_class_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="School_Class_Information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Class",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteAbout",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Title"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                        verbose_name="School Short Description",
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                        verbose_name="School Long Description",
                    ),
                ),
                ("start_year", models.DateField()),
                (
                    "years_of_experience",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "vision",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="School Vision",
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="School Mission",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_about_slug,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website About",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteHomeSliderContent",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_home_slider_content_slug,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website Home Slider Content",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "logo",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_school_website_logo,
                    ),
                ),
                (
                    "favicon",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_school_website_favicon,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core.utills.get_school_website_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_website_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website Information",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteHomeSliderContentFile",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_home_slider_content_image,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_home_slider_content_file_slug,
                        unique=True,
                    ),
                ),
                (
                    "home_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="home_content_info",
                        to="core.websitehomeslidercontent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website Home Slider Content File",
            },
            bases=("core.universalmodel",),
        ),
        migrations.AddField(
            model_name="websitehomeslidercontent",
            name="website_home_slider_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="school_website_slider_information",
                to="core.websiteinformation",
            ),
        ),
        migrations.CreateModel(
            name="WebsiteFunFactContent",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "years_of_experience",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "number_of_students",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "number_of_alumni",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "winning_awards",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "about_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="about_fun_fact_content",
                        to="core.websiteabout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website Fun Fact Content",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteAboutWinningAwards",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "awards_image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_about_file_awards_image,
                    ),
                ),
                (
                    "school_award",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_award_process",
                        to="core.websiteabout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website About Winning Awards",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteAboutFile",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_about_file_slug,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_about_file_image,
                    ),
                ),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="website_about_file_content",
                        to="core.websiteabout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website About File",
            },
            bases=("core.universalmodel",),
        ),
        migrations.AddField(
            model_name="websiteabout",
            name="website_about_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="school_website_about_information",
                to="core.websiteinformation",
            ),
        ),
        migrations.CreateModel(
            name="SchoolSection",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core.utills.get_school_section_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_class_section",
                        to="core.schoolclass",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Class Section",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SchoolContactInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core.utills.get_school_contact_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_contact_information",
                        to="core.websiteinformation",
                    ),
                ),
                (
                    "school_contact_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_contact_address",
                        to="core.schooladdressinformation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Contact Information",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SchoolAdmission",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("title", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "admission_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("class_one", "Class One"),
                            ("class_two", "Class Two"),
                            ("class_three", "Class Three"),
                            ("class_four", "Class Four"),
                            ("class_five", "Class Five"),
                            ("class_six", "Class Six"),
                            ("class_seven", "Class Seven"),
                            ("class_eight", "Class Eight"),
                            ("class_nine", "Class Nine"),
                            ("class_ten", "Class Ten"),
                            ("class_eleven", "Class Eleven"),
                            ("class_twelve", "Class Twelve"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Admission Class",
                    ),
                ),
                (
                    "admission_branch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prabhati", "প্রভাতী"),
                            ("diba", "দিবা"),
                            ("no_branch", "কোন শাখা নেই"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Admission Branch",
                    ),
                ),
                (
                    "admission_division",
                    models.CharField(
                        blank=True,
                        choices=[("bangla", "বাংলা"), ("english", "ইংরেজি")],
                        max_length=20,
                        null=True,
                        verbose_name="Admission Division",
                    ),
                ),
                (
                    "number_of_seats",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "limit_of_age",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "collection_of_prospectus",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "fill_the_application_form",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "online_admission_form_date_time",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "admission_process_college_information_website",
                    models.URLField(blank=True, null=True),
                ),
                (
                    "digital_lottery_time_information",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "admission_application_rules",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "other_description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("remark", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_admission_pdf,
                        verbose_name="PDF File",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_school_admission_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_admission_process",
                        to="core.websiteinformation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Admission Process",
            },
            bases=("core.universalmodel",),
        ),
        migrations.AddField(
            model_name="schooladdressinformation",
            name="school_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="school_address_information",
                to="core.websiteinformation",
            ),
        ),
        migrations.CreateModel(
            name="AcademicInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("title", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "code_of_conducts",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Code of Conducts",
                    ),
                ),
                (
                    "guideline_for_parents",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Guideline for Parents",
                    ),
                ),
                (
                    "dress_code",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Dress Code",
                    ),
                ),
                (
                    "homework_and_lecture_documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_academic_homework_and_lecture_documents_pdf,
                        verbose_name="Homework and Class Lecture Documents",
                    ),
                ),
                (
                    "lesson_plan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_academic_lesson_plan_documents_pdf,
                        verbose_name="Lesson Plan",
                    ),
                ),
                (
                    "academic_calendar",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_academic_calendar_documents_pdf,
                        verbose_name="Academic Calendar",
                    ),
                ),
                (
                    "syllabus",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_academic_syllabus_documents_pdf,
                        verbose_name="Syllabus",
                    ),
                ),
                (
                    "class_routine",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_school_academic_class_routine_documents_pdf,
                        verbose_name="Class Routine",
                    ),
                ),
                (
                    "co_curricular_activities",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Co-curricular Activities",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_school_academic_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_academic_information",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_academic_information",
                        to="core.websiteinformation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Academic Information",
            },
            bases=("core.universalmodel",),
        ),
    ]
