# Generated by Django 4.2.7 on 2023-12-04 14:45

import core.utills
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebSiteGalleryInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_website_get_gallery_image,
                        verbose_name="Image",
                    ),
                ),
                (
                    "school_website_gallery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_website_gallery_information",
                        to="core.websiteinformation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Website Gallery Images",
                "ordering": ["-createdAt"],
            },
            bases=("core.universalmodel",),
        ),
    ]
