# Generated by Django 5.0 on 2024-01-08 14:16

import autoslug.fields
import core.utills
import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("designation", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_testimonials_image,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_testimonials_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_testimonials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="Testimonials",
                        to="common.schoolinformationonboarding",
                        verbose_name="Testimonials",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonials",
                "verbose_name_plural": "Testimonials",
            },
            bases=("common.basemodel",),
        ),
    ]
