# Generated by Django 4.2.7 on 2023-12-04 15:17

import autoslug.fields
import core.utills
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_websitegalleryinformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsEvents",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "news_events_status",
                    models.CharField(
                        choices=[("news", "News"), ("event", "Event")],
                        db_index=True,
                        default="news",
                        max_length=100,
                        verbose_name="Type",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_news_events_slug,
                        unique=True,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_news_events_image,
                    ),
                ),
                (
                    "school_website_news_events",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_website_news_events_information",
                        to="core.websiteinformation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "News and Events",
                "ordering": ["-publish_date"],
            },
            bases=("core.universalmodel",),
        ),
    ]
