# Generated by Django 5.0 on 2024-01-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_testimonials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
