# Generated by Django 4.2.7 on 2023-12-04 15:39

import autoslug.fields
import core.utills
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_newsevents"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "school_blog_tag_website_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="blog_tags",
                        to="core.websiteinformation",
                        verbose_name="School Website Blog Tag",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "school_blog_category_website_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="blog_categories",
                        to="core.websiteinformation",
                        verbose_name="School Website Blog Category",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_blog_slug,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Content"),
                ),
                ("publish_date", models.DateTimeField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="core.blogcategory", verbose_name="Categories"
                    ),
                ),
                (
                    "school_blog_website_information",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_website_blog_information",
                        to="core.websiteinformation",
                        verbose_name="School Website Blog Information",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="core.blogtag", verbose_name="Tags"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Blog Posts",
                "ordering": ["-publish_date"],
            },
            bases=("core.universalmodel",),
        ),
    ]
