# Generated by Django 5.0 on 2024-01-23 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudentApp", "0001_initial"),
        ("TeacherApp", "0001_initial"),
        ("common", "0001_initial"),
        ("core", "0003_alter_schoolclass_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="absent_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="class_teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="class_teachers",
                to="TeacherApp.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="present_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="total_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ClassAttendance",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("is_present", models.BooleanField(default=False)),
                ("on_leave", models.BooleanField(default=True)),
                ("date", models.DateTimeField()),
                ("late_arrival", models.BooleanField(default=False)),
                ("early_departure", models.BooleanField(default=False)),
                ("leave_reason", models.CharField(blank=True, max_length=255)),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[("STUDENT", "Student"), ("TEACHER", "Teacher")],
                        default="STUDENT",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "attendance_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="class_attendances",
                        to="core.schoolclass",
                    ),
                ),
                (
                    "attendance_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="section_attendances",
                        to="core.schoolsection",
                    ),
                ),
                (
                    "attendance_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="attendant_students",
                        to="StudentApp.student",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_attendances",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
