# Generated by Django 4.2.7 on 2023-12-04 15:50

import autoslug.fields
import core.utills
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_blogtag_blogcategory_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, null=True, verbose_name="Facebook URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, null=True, verbose_name="Twitter URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Instagram URL"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_social_media_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_social_media_website_information",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_info",
                        to="core.websiteinformation",
                        verbose_name="SocialMedia Website Information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Social Media Information",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="AlumniSection",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_alumni_section_slug,
                        unique=True,
                    ),
                ),
                (
                    "about_alumni",
                    models.TextField(
                        blank=True, null=True, verbose_name="About Alumni"
                    ),
                ),
                (
                    "alumni_events",
                    models.TextField(
                        blank=True, null=True, verbose_name="Alumni Events"
                    ),
                ),
                (
                    "alumni_news",
                    models.TextField(blank=True, null=True, verbose_name="Alumni News"),
                ),
                (
                    "school_alumni_section_website_information",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_section_info",
                        to="core.websiteinformation",
                        verbose_name="School Website Alumni Information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Alumni Section Information",
            },
            bases=("core.universalmodel",),
        ),
    ]
