# Generated by Django 5.0 on 2024-01-24 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TeacherApp", "0001_initial"),
        ("core", "0004_schoolclass_absent_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="class_teachers",
                to="TeacherApp.teacher",
            ),
        ),
    ]
