# Generated by Django 5.0 on 2024-01-30 15:24

import autoslug.fields
import core.utills
import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_schoolclass_class_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniSectionImage",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_alumni_section_slug,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utills.get_alumni_section_image_slug,
                    ),
                ),
                (
                    "alumni_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_section_images",
                        to="core.alumnisection",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
