# Generated by Django 4.2.7 on 2023-12-04 17:12

import autoslug.fields
import core.utills
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_socialmedia_alumnisection"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteTeacherInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_teacher_slug,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255, verbose_name="Position")),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Biography"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "school_teacher_website_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="teachers",
                        to="core.websiteinformation",
                        verbose_name="School Website Teacher Information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Teachers",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteStaffInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_staff_slug,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255, verbose_name="Position")),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Biography"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "school_staff_website_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="staff",
                        to="core.websiteinformation",
                        verbose_name="School Website Staff Information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff Members",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebsiteManagingCommitteeMemberInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_managing_committee_member_slug,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255, verbose_name="Position")),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Biography"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "school_managing_committee_member_website_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ManagingCommitteeMember",
                        to="core.websiteinformation",
                        verbose_name="School Website ManagingCommitteeMember Information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ManagingCommitteeMember",
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="WebSiteFacultyInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utills.get_website_faculty_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_faculty_website_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="faculty_members",
                        to="core.websiteinformation",
                        verbose_name="School Faculty Website Information",
                    ),
                ),
                (
                    "staff_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="faculty_membership",
                        to="core.websitemanagingcommitteememberinformation",
                        verbose_name="Staff Members",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="faculty_membership",
                        to="core.websiteteacherinformation",
                        verbose_name="Teachers",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Faculty Members",
            },
            bases=("core.universalmodel",),
        ),
    ]
