# Generated by Django 4.2.7 on 2023-12-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_websiteteacherinformation_websitestaffinformation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitefacultyinformation",
            name="managing_committee_member",
            field=models.ManyToManyField(
                blank=True,
                related_name="Managing_Committee_Member_Information",
                to="core.websitemanagingcommitteememberinformation",
            ),
        ),
    ]
