# Generated by Django 5.0 on 2024-01-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alumnisectionimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitefacultyinformation",
            name="staff_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="faculty_membership",
                to="core.websitestaffinformation",
                verbose_name="Staff Members",
            ),
        ),
    ]
