# Generated by Django 5.0 on 2023-12-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("core", "0007_websitefacultyinformation_managing_committee_member"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="schooladdressinformation",
            index=models.Index(
                fields=["school_address"], name="core_school_school__d80be4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolcontactinformation",
            index=models.Index(
                fields=["school_contact"], name="core_school_school__553fe0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolcontactinformation",
            index=models.Index(
                fields=["school_contact_address"], name="core_school_school__fafa28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="websiteinformation",
            index=models.Index(
                fields=["school_website"], name="core_websit_school__f9f31b_idx"
            ),
        ),
    ]
