# Generated by Django 5.0 on 2024-03-13 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_schoolinformationonboarding_username"),
        ("core", "0007_alter_websitefacultyinformation_staff_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="websiteinformation",
            name="school_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="school_address_information",
                to="core.schooladdressinformation",
            ),
        ),
        migrations.AddField(
            model_name="websiteinformation",
            name="school_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="school_contact_information",
                to="core.schoolcontactinformation",
            ),
        ),
        migrations.AlterField(
            model_name="websiteinformation",
            name="school_website",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="school_website_information",
                to="common.schoolinformationonboarding",
            ),
        ),
    ]
