# Generated by Django 5.0 on 2024-03-17 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_schoolinformationonboarding_username"),
        ("core", "0008_websiteinformation_school_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="school_blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="school_website_blog_information",
                to="common.schoolinformationonboarding",
                verbose_name="School Website Blog Information",
            ),
        ),
    ]
