# Generated by Django 5.0 on 2023-12-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('core', '0008_schooladdressinformation_core_school_school__d80be4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevents',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_schools', to='common.schoolinformationonboarding'),
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='school_website_news_events',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school_website_news_events_information', to='core.websiteinformation'),
        ),
    ]
