# Generated by Django 5.0 on 2024-03-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_schoolinformationonboarding_username"),
        ("core", "0009_alter_blog_school_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicinformation",
            name="school_academic_information",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_academic_information",
                to="common.schoolinformationonboarding",
            ),
        ),
        migrations.AlterField(
            model_name="websitegalleryinformation",
            name="school_website_gallery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_website_gallery_information",
                to="common.schoolinformationonboarding",
            ),
        ),
    ]
