# Generated by Django 5.0 on 2024-04-27 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_schoolinformationonboarding_username'),
        ('core', '0010_alter_academicinformation_school_academic_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='school_social_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_info', to='common.schoolinformationonboarding', verbose_name='SocialMedia Website Information'),
        ),
    ]
