# Generated by Django 4.2.7 on 2023-12-01 13:55

import TeacherApp.utills
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("teacher_id", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_Of_birth", models.DateField(blank=True, null=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                ("joining_date", models.DateTimeField(blank=True, null=True)),
                ("qualification", models.TextField(blank=True, null=True)),
                ("experience", models.TextField(blank=True, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=TeacherApp.utills.get_school_teacher_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="teacher_school_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "teacher_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_teacher_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="TeacherImage",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=TeacherApp.utills.get_school_teacher_image_slug,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=TeacherApp.utills.get_teacher_profile_image,
                    ),
                ),
                (
                    "teacher_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="teacher_information",
                        to="TeacherApp.teacher",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
