# Generated by Django 4.2.7 on 2023-12-01 13:55

import StudentApp.utills
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_Of_birth", models.DateField(blank=True, null=True)),
                (
                    "blood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A Positive"),
                            ("A-", "A Negative"),
                            ("B+", "B Positive"),
                            ("B-", "B Negative"),
                            ("AB+", "AB Positive"),
                            ("AB-", "AB Negative"),
                            ("O+", "O Positive"),
                            ("O-", "O Negative"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Islam", "Islam"),
                            ("Christianity", "Christianity"),
                            ("Hinduism", "Hinduism"),
                            ("Buddhism", "Buddhism"),
                            ("Judaism", "Judaism"),
                            ("Sikhism", "Sikhism"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "admission_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=StudentApp.utills.get_school_student_slug,
                        unique=True,
                    ),
                ),
                (
                    "student_name_bangla",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "student_name_english_captial",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "birth_certificate_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "birth_of_place",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Owen district as follow birth_certificate",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("married", "Married"),
                            ("unmarried", "Unmarried"),
                            ("widowed", "Widowed"),
                            ("custom", "Custom (বিপত্নীক etc.)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "disability_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_disability", "No Disability"),
                            ("visual_impairment", "Visual Impairment"),
                            ("hearing_impairment", "Hearing Impairment"),
                            ("mobility_impairment", "Mobility Impairment"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ethnic_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bengali", "Bengali"),
                            ("chakma", "Chakma"),
                            ("garo", "Garo"),
                            ("marma", "Marma"),
                            ("santal", "Santal"),
                            ("rakhine", "Rakhine"),
                            ("bawm", "Bawm"),
                            ("mro", "Mro"),
                            ("mizo", "Mizo"),
                            ("tripuri", "Tripuri"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "school_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_school_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "student_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_student_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("nid", models.CharField(blank=True, max_length=255, null=True)),
                ("occupation", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "guardian_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("grandfather", "Grandfather"),
                            ("grandmother", "Grandmother"),
                            ("brother", "Brother"),
                            ("uncle", "Uncle"),
                            ("brother_in_law", "Brother-in-law"),
                            ("sister", "Sister"),
                            ("sister_in_law", "Sister-in-law"),
                            ("legal_guardian", "Legal Guardian"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="StudentPresentAddress",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=StudentApp.utills.get_student_present_address_slug,
                        unique=True,
                    ),
                ),
                ("divisions", models.CharField(blank=True, max_length=255, null=True)),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "upazila",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Upozila or Thana",
                    ),
                ),
                (
                    "pourashava",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pourashava or City Corporation",
                    ),
                ),
                (
                    "union_parishad",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ward", models.CharField(blank=True, max_length=255, null=True)),
                ("mouza", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "village",
                    models.TextField(
                        blank=True,
                        max_length=555,
                        null=True,
                        verbose_name="Rasta/village",
                    ),
                ),
                (
                    "house_holding_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "post_office",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("post_code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "student_present_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_present_address_information",
                        to="StudentApp.student",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="StudentPermanentAddress",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=StudentApp.utills.get_student_permanent_address_slug,
                        unique=True,
                    ),
                ),
                ("divisions", models.CharField(blank=True, max_length=255, null=True)),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "upazila",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Upozila or Thana",
                    ),
                ),
                (
                    "pourashava",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pourashava or City Corporation",
                    ),
                ),
                (
                    "union_parishad",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ward", models.CharField(blank=True, max_length=255, null=True)),
                ("mouza", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "village",
                    models.TextField(
                        blank=True,
                        max_length=555,
                        null=True,
                        verbose_name="Rasta/village",
                    ),
                ),
                (
                    "house_holding_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "post_office",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("post_code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "student_permanent_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_permanent_address_information",
                        to="StudentApp.student",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="StudentMother",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "name_bangla",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "name_english_capital",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nid", models.CharField(blank=True, max_length=255, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "birth_certificate_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mother_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alive", "Alive"),
                            ("deceased", "Deceased"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_of_death", models.DateField(blank=True, null=True)),
                (
                    "student_mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_mother_information",
                        to="StudentApp.student",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="StudentImage",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=StudentApp.utills.get_school_student_image_slug,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=StudentApp.utills.get_student_profile_image,
                    ),
                ),
                (
                    "student_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_information",
                        to="StudentApp.student",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="StudentFather",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "name_bangla",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "name_english_capital",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nid", models.CharField(blank=True, max_length=255, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "birth_certificate_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "father_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alive", "Alive"),
                            ("deceased", "Deceased"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_of_death", models.DateField(blank=True, null=True)),
                (
                    "student_father",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_father_information",
                        to="StudentApp.student",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="StudentCurrentStatus",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=StudentApp.utills.get_school_student_current_slug,
                        unique=True,
                    ),
                ),
                (
                    "class_roll_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "current_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_current_class",
                        to="core.schoolclass",
                    ),
                ),
                (
                    "current_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_current_section",
                        to="core.schoolsection",
                    ),
                ),
                (
                    "student_current_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_current_status_information",
                        to="StudentApp.student",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
