# Generated by Django 5.0 on 2024-01-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("StudentApp", "0001_initial"),
        ("core", "0004_schoolclass_absent_students_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentcurrentstatus",
            unique_together={
                ("current_class", "current_section", "student_current_status")
            },
        ),
    ]
