# Generated by Django 5.0 on 2024-02-05 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudentApp", "0002_alter_studentcurrentstatus_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentguardian",
            name="student_guardian",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_guardian_information",
                to="StudentApp.student",
            ),
            preserve_default=False,
        ),
    ]
