# Generated by Django 5.0 on 2024-02-15 14:38

import SubscriptionApp.utills
import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("core", "0007_alter_websitefacultyinformation_staff_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the subscription plan.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SubscriptionApp.utills.get_school_subscription_plan_slug,
                        unique=True,
                    ),
                ),
                ("duration_months", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SubscriptionApp.utills.get_school_subscription_slug,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "school_subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_subscription",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_subscription_plan",
                        to="SubscriptionApp.subscriptionplan",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
