# Generated by Django 5.0 on 2024-02-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SubscriptionApp", "0001_initial"),
        ("common", "0001_initial"),
        ("core", "0007_alter_websitefacultyinformation_staff_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_id", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=55, null=True)),
                ("card_no", models.CharField(max_length=55, null=True)),
                ("card_type", models.CharField(max_length=150)),
                ("bank_tran_id", models.CharField(max_length=155, null=True)),
                ("currency", models.CharField(default="BDT", max_length=10)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        default="failed",
                        max_length=10,
                    ),
                ),
                (
                    "school_transaction",
                    models.ForeignKey(
                        help_text="The school associated with this transaction.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_transactions",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subscription_plans",
                        to="SubscriptionApp.subscriptionplan",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
