# Generated by Django 5.0 on 2024-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SubscriptionApp", "0002_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="invoice_number",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
