# Generated by Django 5.0 on 2024-01-13 15:19

import SchoolAdminApp.utills
import autoslug.fields
import django.db.models.deletion
import phonenumber_field.modelfields
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("core", "0002_testimonials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("department_id", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "head_of_department",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "school_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_departments",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=550, null=True)),
                (
                    "experience",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "no_of_vacancies",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("age_limit", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "salary_from",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("salary_to", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("internship", "Internship"),
                            ("temporary", "Temporary"),
                            ("remote", "Remote"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("expired_date", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_career_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_career",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_job_circular",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "career_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="job_department",
                        to="SchoolAdminApp.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Career",
                "ordering": ["-createdAt"],
            },
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("block", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "room_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "room_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal"),
                            ("ac", "AC"),
                            ("suite", "Suite"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "number_of_beds",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cose_per_bed",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("not_available", "Not Available"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_hostel_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_hostel",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_library_slug,
                        unique=True,
                    ),
                ),
                ("book_id", models.CharField(max_length=100)),
                ("book_name", models.CharField(blank=True, max_length=500, null=True)),
                ("language", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "book_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("book", "Book"),
                            ("dvd", "DVD"),
                            ("cd", "CD"),
                            ("newspaper", "Newspaper"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "book_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_stock", "In Stock"),
                            ("out_of_stock", "Out Of Stock"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "library_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="library_classes",
                        to="core.schoolclass",
                    ),
                ),
                (
                    "library_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="library_departments",
                        to="SchoolAdminApp.department",
                    ),
                ),
                (
                    "school_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_libraries",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_product_category_slug,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "school_product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_product_categories",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_product_slug,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "school_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_products",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_product_categories_info",
                        to="SchoolAdminApp.productcategory",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SchoolAdmin",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_Of_birth", models.DateField(blank=True, null=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                ("joining_date", models.DateTimeField(blank=True, null=True)),
                ("qualification", models.TextField(blank=True, null=True)),
                ("experience", models.TextField(blank=True, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_admin_slug,
                        unique=True,
                    ),
                ),
                (
                    "schoolUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_school_admin_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_admin_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SchoolAdminImage",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_admin_image_slug,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=SchoolAdminApp.utills.get_admin_profile_image,
                    ),
                ),
                (
                    "school_admin_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_admin_information",
                        to="SchoolAdminApp.schooladmin",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SportsInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("sports_id", models.CharField(max_length=100)),
                (
                    "sports_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("coach_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "started_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_sports_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_sports",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_sports",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("subject_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "class_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="class_subject_information",
                        to="core.schoolclass",
                    ),
                ),
                (
                    "school_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_subject_information",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("fees", models.CharField(blank=True, max_length=255, null=True)),
                ("exam_start_time", models.TimeField(blank=True, null=True)),
                ("exam_end_time", models.TimeField(blank=True, null=True)),
                ("exam_date", models.DateTimeField(blank=True, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_exam_slug,
                        unique=True,
                    ),
                ),
                (
                    "exam_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="exam_classes",
                        to="core.schoolclass",
                    ),
                ),
                (
                    "exam_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="exam_sections",
                        to="core.schoolsection",
                    ),
                ),
                (
                    "school_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_exams",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "exam_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_exam_subjects",
                        to="SchoolAdminApp.subject",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="ClassTimeTable",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("class_date", models.DateTimeField(blank=True, null=True)),
                ("class_start_time", models.TimeField(blank=True, null=True)),
                ("class_end_time", models.TimeField(blank=True, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_class_time_table_slug,
                        unique=True,
                    ),
                ),
                (
                    "school_class_time_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_class_time_table",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "school_section_time_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_section_information",
                        to="core.schoolsection",
                    ),
                ),
                (
                    "school_time_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_class_information",
                        to="core.schoolclass",
                    ),
                ),
                (
                    "class_time_table_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_class_time_table_subjects",
                        to="SchoolAdminApp.subject",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_transport_slug,
                        unique=True,
                    ),
                ),
                ("route_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "vehicle_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "driver_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("driver_address", models.TextField(blank=True, null=True)),
                (
                    "school_transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_transports",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_vendor_slug,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "school_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_vendors",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "purchase_request_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validate", "Validated"),
                            ("approved", "Approved"),
                            ("ordered", "Ordered"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_purchase_request_slug,
                        unique=True,
                    ),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "amount_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note_private", models.TextField(blank=True, null=True)),
                ("note_public", models.TextField(blank=True, null=True)),
                (
                    "product_request",
                    models.ManyToManyField(
                        related_name="product_requests", to="SchoolAdminApp.product"
                    ),
                ),
                (
                    "school_purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_purchases_request",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "purchase_request_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchase_request_vendors",
                        to="SchoolAdminApp.vendor",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="PurchaseReceived",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "purchase_received_status",
                    models.CharField(
                        choices=[
                            ("partially_received", "Partially Received"),
                            ("all_received", "All Received"),
                            ("cancelled", "Cancelled"),
                            ("refused", "Refused"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_purchase_received_slug,
                        unique=True,
                    ),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "partially_received",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("all_received", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "amount_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note_private", models.TextField(blank=True, null=True)),
                ("note_public", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="product_received", to="SchoolAdminApp.product"
                    ),
                ),
                (
                    "school_purchase_received",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_purchases_received",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchase_requests",
                        to="SchoolAdminApp.purchaserequest",
                    ),
                ),
                (
                    "purchase_received_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchase_received_vendors",
                        to="SchoolAdminApp.vendor",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
