# Generated by Django 4.2.7 on 2023-12-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SchoolAdminApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schooladminimage",
            name="school_admin_info",
        ),
        migrations.RemoveField(
            model_name="schooladminimage",
            name="universalmodel_ptr",
        ),
        migrations.DeleteModel(
            name="SchoolAdmin",
        ),
        migrations.DeleteModel(
            name="SchoolAdminImage",
        ),
    ]
