# Generated by Django 5.0 on 2024-01-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchoolAdminApp", "0003_initial"),
        ("common", "0001_initial"),
        ("core", "0002_testimonials"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("department_id", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "head_of_department",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "school_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_departments",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=550, null=True)),
                (
                    "experience",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "no_of_vacancies",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("age_limit", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "salary_from",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("salary_to", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("internship", "Internship"),
                            ("temporary", "Temporary"),
                            ("remote", "Remote"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("expired_date", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "school_career",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_job_circular",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "career_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="job_department",
                        to="SchoolAdminApp.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Career",
                "ordering": ["-createdAt"],
            },
            bases=("core.universalmodel",),
        ),
    ]
