# Generated by Django 5.0 on 2024-01-21 13:53

import SchoolAdminApp.utills
import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchoolAdminApp", "0003_alter_result_mark"),
        ("common", "0001_initial"),
        ("core", "0002_testimonials"),
    ]

    operations = [
        migrations.CreateModel(
            name="HolidayManagement",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_holiday_slug,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Holiday Name", max_length=100)),
                (
                    "holiday_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public_holiday", "Public Holiday"),
                            (
                                "government_declared_holidays",
                                "Government Declared Holidays",
                            ),
                            ("religious_holidays", "Religious Holidays"),
                            ("vacation_breaks", "Vacation Breaks"),
                            ("special_occasion_holidays", "Special Occasion Holidays"),
                            ("exam_holiday", "Exam Holiday"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("holiday_start", models.DateField(blank=True, null=True)),
                ("holiday_end", models.DateField(blank=True, null=True)),
                (
                    "school_holiday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_holidays",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
