# Generated by Django 5.0 on 2024-01-21 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchoolAdminApp", "0004_holidaymanagement"),
        ("common", "0001_initial"),
        ("core", "0002_testimonials"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeesCategory",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(help_text="Fees Name", max_length=100)),
                (
                    "school_fees",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_fees",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="FeesInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "fees_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fees_start", models.DateField(blank=True, null=True)),
                ("fees_end", models.DateField(blank=True, null=True)),
                (
                    "fees_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_fees_category",
                        to="SchoolAdminApp.feescategory",
                    ),
                ),
                (
                    "fess_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fess_classes",
                        to="core.schoolclass",
                    ),
                ),
                (
                    "fess_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fess_sections",
                        to="core.schoolsection",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
