# Generated by Django 5.0 on 2024-01-10 15:15

import SchoolAdminApp.utills
import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchoolAdminApp", "0004_department_career"),
        ("common", "0001_initial"),
        ("core", "0002_testimonials"),
    ]

    operations = [
        migrations.AddField(
            model_name="career",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="1",
                editable=False,
                populate_from=SchoolAdminApp.utills.get_school_career_slug,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ClassTimeTable",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("class_date", models.DateTimeField(blank=True, null=True)),
                ("class_start_time", models.TimeField(blank=True, null=True)),
                ("class_end_time", models.TimeField(blank=True, null=True)),
                (
                    "school_class_time_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_class_time_table",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "school_section_time_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_section_information",
                        to="core.schoolsection",
                    ),
                ),
                (
                    "school_time_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_class_information",
                        to="core.schoolclass",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("block", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "room_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "room_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal"),
                            ("ac", "AC"),
                            ("suite", "Suite"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "number_of_beds",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cose_per_bed",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("not_available", "Not Available"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "school_hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_hostel",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_library_slug,
                        unique=True,
                    ),
                ),
                ("book_id", models.CharField(max_length=100)),
                ("book_name", models.CharField(blank=True, max_length=500, null=True)),
                ("language", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "book_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("book", "Book"),
                            ("dvd", "DVD"),
                            ("cd", "CD"),
                            ("newspaper", "Newspaper"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "book_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_stock", "In Stock"),
                            ("out_of_stock", "Out Of Stock"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "library_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="library_classes",
                        to="core.schoolclass",
                    ),
                ),
                (
                    "library_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="library_departments",
                        to="SchoolAdminApp.department",
                    ),
                ),
                (
                    "school_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_libraries",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="SportsInformation",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("sports_id", models.CharField(max_length=100)),
                (
                    "sports_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("coach_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "started_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "school_sports",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_sports",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_transport_slug,
                        unique=True,
                    ),
                ),
                ("route_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "vehicle_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "driver_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("driver_address", models.TextField(blank=True, null=True)),
                (
                    "school_transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_transports",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
