# Generated by Django 5.0 on 2024-01-10 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchoolAdminApp", "0005_career_slug_classtimetable_hostel_library_and_more"),
        ("common", "0001_initial"),
        ("core", "0002_testimonials"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("fees", models.CharField(blank=True, max_length=255, null=True)),
                ("exam_start_time", models.TimeField(blank=True, null=True)),
                ("exam_end_time", models.TimeField(blank=True, null=True)),
                ("exam_date", models.DateTimeField(blank=True, null=True)),
                (
                    "exam_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="exam_classes",
                        to="core.schoolclass",
                    ),
                ),
                (
                    "exam_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="exam_sections",
                        to="core.schoolsection",
                    ),
                ),
                (
                    "school_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_exams",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
