# Generated by Django 5.0 on 2024-01-22 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchoolAdminApp", "0005_feescategory_feesinformation"),
        ("StudentApp", "0001_initial"),
        ("common", "0001_initial"),
        ("core", "0002_testimonials"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeesCollection",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "fees_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("paid_date", models.DateField(auto_now_add=True)),
                (
                    "fees_collection_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fees_collection_category",
                        to="SchoolAdminApp.feescategory",
                    ),
                ),
                (
                    "school_fees_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_fees_collection",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "student_fees_collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fees_collection_students",
                        to="StudentApp.student",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
