# Generated by Django 5.0 on 2024-01-12 11:25

import SchoolAdminApp.utills
import autoslug.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchoolAdminApp", "0006_exam"),
        ("common", "0001_initial"),
        ("core", "0002_testimonials"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_product_category_slug,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "school_product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_product_categories",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_product_slug,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "school_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_products",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_product_categories_info",
                        to="SchoolAdminApp.productcategory",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_vendor_slug,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "school_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_vendors",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "purchase_request_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validate", "Validated"),
                            ("approved", "Approved"),
                            ("ordered", "Ordered"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_purchase_request_slug,
                        unique=True,
                    ),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "amount_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note_private", models.TextField(blank=True, null=True)),
                ("note_public", models.TextField(blank=True, null=True)),
                (
                    "product_request",
                    models.ManyToManyField(
                        related_name="product_requests", to="SchoolAdminApp.product"
                    ),
                ),
                (
                    "school_purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_purchases_request",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "purchase_request_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchase_request_vendors",
                        to="SchoolAdminApp.vendor",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
        migrations.CreateModel(
            name="PurchaseReceived",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "purchase_received_status",
                    models.CharField(
                        choices=[
                            ("partially_received", "Partially Received"),
                            ("all_received", "All Received"),
                            ("cancelled", "Cancelled"),
                            ("refused", "Refused"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_school_purchase_received_slug,
                        unique=True,
                    ),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "partially_received",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("all_received", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "amount_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note_private", models.TextField(blank=True, null=True)),
                ("note_public", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="product_received", to="SchoolAdminApp.product"
                    ),
                ),
                (
                    "school_purchase_received",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_purchases_received",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchase_requests",
                        to="SchoolAdminApp.purchaserequest",
                    ),
                ),
                (
                    "purchase_received_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchase_received_vendors",
                        to="SchoolAdminApp.vendor",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
