# Generated by Django 5.0 on 2024-01-26 17:19

import SchoolAdminApp.utills
import autoslug.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchoolAdminApp", "0006_feescollection"),
        ("common", "0001_initial"),
        ("core", "0005_alter_schoolclass_class_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeCandidate",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=500,
                        null=True,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "portfolio_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Portfolio Link"
                    ),
                ),
                (
                    "linkedin_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="LinkedIn Profile Link"
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "curriculum_vitae",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=SchoolAdminApp.utills.get_curriculum_vitae_file,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=SchoolAdminApp.utills.get_employee_candidate_slug,
                        unique=True,
                    ),
                ),
                (
                    "job_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="apply_job",
                        to="SchoolAdminApp.career",
                    ),
                ),
                (
                    "school_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_candidate",
                        to="common.schoolinformationonboarding",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
