# Generated by Django 5.0 on 2024-02-02 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SchoolAdminApp", "0007_employeecandidate"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradingconfig",
            name="letter_grade_A",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="gradingconfig",
            name="letter_grade_A_minus",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="gradingconfig",
            name="letter_grade_A_plus",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="gradingconfig",
            name="letter_grade_B",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="gradingconfig",
            name="letter_grade_C",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="gradingconfig",
            name="letter_grade_D",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="gradingconfig",
            name="letter_grade_F",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="gradingconfig",
            name="school_grading",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="school_grading_info",
                to="common.schoolinformationonboarding",
            ),
        ),
    ]
