# Generated by Django 5.0 on 2024-02-11 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SchoolAdminApp", "0009_result_gpa_result_grade"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentSubjectResult",
        ),
    ]
