# Generated by Django 5.0 on 2024-03-21 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SchoolAdminApp", "0010_delete_studentsubjectresult"),
        ("StudentApp", "0003_studentguardian_student_guardian"),
        ("common", "0002_schoolinformationonboarding_username"),
        ("core", "0009_alter_blog_school_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "student_passing_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "student_gpa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "student_session",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("student_roll", models.IntegerField(blank=True, null=True)),
                ("student_reg", models.IntegerField(blank=True, null=True)),
                (
                    "student_board",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "student_exam_center",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "testimonial_serial_number",
                    models.IntegerField(blank=True, null=True),
                ),
                ("testimonial_issue_date", models.DateField(blank=True, null=True)),
                (
                    "school_testimonial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_testimonials",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "student_testimonial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_testimonials",
                        to="StudentApp.student",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
