# Generated by Django 5.0 on 2024-04-23 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SchoolAdminApp", "0011_testimonial"),
        ("StudentApp", "0003_studentguardian_student_guardian"),
        ("common", "0002_schoolinformationonboarding_username"),
        ("core", "0010_alter_academicinformation_school_academic_information_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolResult",
            fields=[
                (
                    "universalmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.universalmodel",
                    ),
                ),
                (
                    "total_marks",
                    models.IntegerField(blank=True, help_text="Total Marks", null=True),
                ),
                (
                    "cgpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "failed_subjects_result",
                    models.ManyToManyField(
                        blank=True,
                        related_name="failed_subjects_results",
                        to="SchoolAdminApp.result",
                    ),
                ),
                (
                    "passed_subjects_result",
                    models.ManyToManyField(
                        blank=True,
                        related_name="passed_subjects_results",
                        to="SchoolAdminApp.result",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_student_results",
                        to="common.schoolinformationonboarding",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="class_student_results",
                        to="core.schoolclass",
                    ),
                ),
                (
                    "school_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="section_student_results",
                        to="core.schoolsection",
                    ),
                ),
                (
                    "school_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="semester_student_results",
                        to="SchoolAdminApp.semester",
                    ),
                ),
                (
                    "school_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_results",
                        to="StudentApp.student",
                    ),
                ),
            ],
            bases=("core.universalmodel",),
        ),
    ]
