version: '3'

volumes:
  django_db:
  media_volume:  

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: project101
      POSTGRES_USER: tasim
      POSTGRES_PASSWORD: tasim*#2024
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - django_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
